name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git unzip expect \
          autoconf automake libtool pkg-config zlib1g-dev \
          libncurses5-dev libgdbm-dev libnss3-dev \
          libreadline-dev libsqlite3-dev libssl-dev libffi-dev

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install cython==0.29.33 buildozer

    - name: Install Android SDK and required packages
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        curl -O https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip commandlinetools-linux-*.zip
        mv cmdline-tools latest

        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

        yes | sdkmanager --licenses
        sdkmanager --update
        sdkmanager "platform-tools" "build-tools;33.0.2" "platforms;android-33"

    - name: Build APK
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
        buildozer android debug

    - name: List build output
      run: |
        echo "=== BIN DIRECTORY ==="
        ls -la bin/ || echo "bin/ directory not found"
        echo "=== APK FILES ==="
        find . -name "*.apk" -type f || echo "No APKs found"

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ASL-Mobile-App-APK
        path: bin/*.apk
        retention-days: 30
